import Router from "express";
import * as authController from "./controller/auth.js";
import * as validators from "./validation.js";
import { validation } from "../../middleware/validation.js";
const router = Router();
router.post("/signup", validation(validators.signUp), authController.signUp);
router.get("/confirmEmail/:token", authController.confirmEmail);
router.get("/newConfirmEmail/:token", authController.newConfirmEmail);
router.post("/login", validation(validators.login), authController.logIn);
export default router;
